### ISSUE TITLE
Classes not autoloading from composer

### ISSUE THREAD

**Issue by lstanard** [bokkagroup/atom#12]
I believe we need to include `require __DIR__ . '/vendor/autoload.php';` somewhere in the theme (probably functions.php?)

**Comment by lstanard** [comment]
@mikemcguire we're using 2 different composer.json files and have 2 different vendor directories. For the classes we're wanting to autoload here at the theme level I think we could put `require __DIR__ . '/vendor/autoload.php';` into `functions.php` since we aren't loading any dependencies at this point that are needed by any plugins – this is just loading our classes. 

If we're wanting to autoload classes from our plugins we would then also need to add that autoload entry point somewhere else within the site, but we could address that as part of the boilerplate setup.

**Comment by mikemcguire** [comment]
You only need to  load the generated autoloader once per application. If you look at Atom's composer.json it give instructions to composer on where to autoload it's classes from and composer will do all of the magic for you. When you install atom as a dependency it will install atom's dependencies in the same vendor directory as the top level application dependencies. Let me get a working example up for you to take a look at so it makes more sense..

**Comment by lstanard** [comment]
That makes sense. Since I didn't use the boilerplate composer file to install I ran `composer install` directly from the theme and it wasn't looking in the right place
